/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Greet: typeof import('./../components/Greet.vue')['default']
    'IconIc:sharpAddCircleOutline': typeof import('~icons/ic/sharp-add-circle-outline')['default']
    'IconIc:sharpRemoveCircleOutline': typeof import('~icons/ic/sharp-remove-circle-outline')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
