name: Check Frontend

on:
  push:
    branches: [main]
    paths-ignore:
      - 'src-tauri/**'
      - '**.md'
      - '.github/**'
      - '!/.github/workflows/check-frontend.yml'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'src-tauri/**'
      - '**.md'
      - '.github/**'
      - '!/.github/workflows/check-frontend.yml'

  workflow_dispatch:

jobs:
  check-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pnpm setup
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: TypeCheck
        run: pnpm run check
